const topics = [
  { id: 'throughput', name: 'Throughput', icon: 'TH', summary: 'Volumen de trabajo terminado por período.', intro: 'Medí la capacidad real de salida de un proceso.', cards: [
    { tag: 'Definición', title: '¿Qué es?', text: 'El throughput es la cantidad de unidades de trabajo que un proceso completa durante un período. Las unidades pueden ser pedidos, casos, productos o tareas.', formula: 'Throughput = unidades terminadas / período' },
    { tag: 'Interpretación', title: 'Una medida de salida', text: 'Sirve para saber cuánto entrega el proceso, no cuánto trabajo está en curso. Comparalo con períodos equivalentes y mantené constante la definición de “terminado”.' },
    { tag: 'Error frecuente', title: 'No lo confundas con productividad', text: 'Un throughput alto no siempre implica mayor productividad: puede deberse a más personas, casos más simples o menor calidad. Leélo junto con capacidad y calidad.' }
  ]},
  { id: 'lead-time', name: 'Lead time', icon: 'LT', summary: 'Tiempo total percibido desde el pedido.', intro: 'Entendé cuánto espera un cliente para obtener una respuesta o entrega.', cards: [
    { tag: 'Definición', title: '¿Qué mide?', text: 'El lead time es el tiempo total desde que se solicita un trabajo hasta que se entrega. Incluye las esperas antes de que el equipo comience a trabajar.', formula: 'Lead time = fecha de entrega − fecha de solicitud' },
    { tag: 'Interpretación', title: 'La mirada del cliente', text: 'Representa la experiencia de espera de quien hace la solicitud. Si aumenta, conviene investigar colas, prioridades, dependencias o capacidad.' },
    { tag: 'Error frecuente', title: 'No es solo tiempo activo', text: 'Excluir el tiempo en cola produce una visión incompleta. El lead time incluye todo el recorrido, incluso cuando nadie trabaja activamente en el pedido.' }
  ]},
  { id: 'cycle-time', name: 'Cycle time', icon: 'CT', summary: 'Tiempo activo desde que el trabajo empieza.', intro: 'Aislá la velocidad de ejecución del equipo una vez iniciado el trabajo.', cards: [
    { tag: 'Definición', title: '¿Qué mide?', text: 'El cycle time es el tiempo que transcurre desde que el equipo empieza a trabajar una unidad hasta que la completa.', formula: 'Cycle time = fecha de fin − fecha de inicio de trabajo' },
    { tag: 'Interpretación', title: 'La eficiencia de ejecución', text: 'Ayuda a detectar fricciones dentro del proceso: retrabajos, aprobaciones, bloqueos o pasos innecesarios. Es una métrica de flujo interno.' },
    { tag: 'Error frecuente', title: 'No empieza con el pedido', text: 'Si el cliente espera tres días antes del inicio y el equipo tarda uno en resolver, el cycle time es un día; el lead time es cuatro días.' }
  ]},
  { id: 'backlog', name: 'Backlog', icon: 'BL', summary: 'Trabajo pendiente de completar.', intro: 'Hacé visible la carga acumulada que el proceso todavía debe resolver.', cards: [
    { tag: 'Definición', title: '¿Qué es?', text: 'El backlog es el conjunto o cantidad de ítems solicitados que aún no están terminados. Puede incluir trabajo sin iniciar y trabajo en curso.', formula: 'Backlog = ítems recibidos y no completados' },
    { tag: 'Interpretación', title: 'Una señal de carga y riesgo', text: 'Un backlog que crece de forma sostenida sugiere que la entrada supera la capacidad de salida. Segmentalo por antigüedad, prioridad y tipo de caso.' },
    { tag: 'Error frecuente', title: 'El total no cuenta toda la historia', text: 'Dos backlogs del mismo tamaño pueden tener riesgos distintos. Uno con casos recién ingresados no equivale a otro con solicitudes críticas atrasadas.' }
  ]},
  { id: 'sla', name: 'SLA', icon: 'SLA', summary: 'Compromiso de nivel de servicio.', intro: 'SeguÍ si la operación cumple los plazos o estándares prometidos.', cards: [
    { tag: 'Definición', title: '¿Qué es?', text: 'Un SLA (Service Level Agreement) define un compromiso medible de servicio: por ejemplo, resolver el 90% de tickets críticos en menos de cuatro horas.', formula: '% cumplimiento = ítems dentro de SLA / ítems elegibles × 100' },
    { tag: 'Interpretación', title: 'Cumplimiento frente a un acuerdo', text: 'No mide solo velocidad: compara el desempeño con una promesa o estándar explícito. Siempre especificá población, período y condición de cumplimiento.' },
    { tag: 'Error frecuente', title: 'Promediar puede ocultar incumplimientos', text: 'Un tiempo promedio bajo no garantiza cumplimiento de SLA. Reportá el porcentaje de casos dentro del umbral y analizá los casos incumplidos.' }
  ]}
];

const questionBank = {
  throughput: [
    ['¿Qué expresa mejor el throughput?', ['El tiempo total que espera un cliente', 'La cantidad de unidades completadas en un período', 'El trabajo que aún no comenzó', 'El porcentaje de casos dentro de un acuerdo'], 1, 'Throughput mide salida: cuántas unidades se completaron durante un período.'],
    ['Un equipo cerró 120 solicitudes en una semana. ¿Cuál fue su throughput semanal?', ['120 solicitudes', '120 horas', '1 semana por solicitud', 'No se puede calcular'], 0, 'La unidad terminada es la solicitud y el período es la semana: el throughput es 120 solicitudes semanales.'],
    ['¿Por qué un throughput alto no prueba por sí solo una mayor productividad?', ['Porque puede haber cambiado la cantidad de personas o la complejidad de los casos', 'Porque throughput siempre mide calidad', 'Porque solo puede calcularse anualmente', 'Porque excluye las unidades terminadas'], 0, 'Más salida puede provenir de mayor capacidad o de trabajo más simple; requiere contexto para interpretarse.'],
    ['¿Cuál es la mejor métrica complementaria para evitar leer throughput de forma aislada?', ['Calidad del resultado', 'Nombre del equipo', 'Fecha de creación del reporte', 'Color del dashboard'], 0, 'La calidad permite verificar que un mayor volumen entregado no se obtuvo deteriorando el resultado.'],
    ['Si entran 100 pedidos y se terminan 80 por semana, ¿qué indica un throughput de 80?', ['La operación elimina más trabajo del que recibe', 'Se completan 80 pedidos por semana', 'Todos los pedidos cumplen SLA', 'El lead time es de 80 días'], 1, 'El throughput solo describe las 80 unidades completadas en ese período.'],
    ['¿Qué debe permanecer consistente al comparar throughput entre meses?', ['La definición de “unidad terminada”', 'El diseño visual del gráfico', 'El nombre del analista', 'El día de publicación'], 0, 'Cambiar qué cuenta como terminado vuelve engañosa cualquier comparación de throughput.']
  ],
  'lead-time': [
    ['¿Desde cuándo se mide el lead time?', ['Desde que el equipo inicia el trabajo', 'Desde que el cliente solicita el trabajo', 'Desde que el reporte se publica', 'Desde la última revisión'], 1, 'El lead time representa la espera completa desde la solicitud hasta la entrega.'],
    ['¿Qué incluye el lead time que el cycle time no necesariamente incluye?', ['Tiempo de espera antes de iniciar el trabajo', 'El tiempo de ejecución', 'La fecha de entrega', 'Las unidades completadas'], 0, 'La cola previa al inicio forma parte de la espera total del cliente.'],
    ['Una solicitud entra el lunes, se empieza el jueves y se entrega el viernes. ¿Qué métrica refleja los cuatro días de espera?', ['Lead time', 'Cycle time', 'Throughput', 'SLA'], 0, 'El lead time cubre desde el lunes, fecha de solicitud, hasta la entrega del viernes.'],
    ['Si el lead time aumenta pero el cycle time permanece estable, una hipótesis inicial razonable es:', ['Hay más espera o cola antes de iniciar', 'El equipo resuelve más rápido', 'El backlog desapareció', 'El SLA ya no aplica'], 0, 'La ejecución no cambió, por lo que conviene investigar la espera previa o dependencias.'],
    ['¿Para quién representa especialmente la experiencia el lead time?', ['Para quien solicita el trabajo', 'Solo para el analista financiero', 'Solo para el proveedor de software', 'Para nadie externo al proceso'], 0, 'Describe cuánto espera la persona o área que hizo la solicitud.'],
    ['¿Cuál es un error al calcular lead time?', ['Excluir los días que el ítem estuvo en cola', 'Registrar fecha de solicitud', 'Registrar fecha de entrega', 'Usar una unidad de tiempo consistente'], 0, 'Quitar la cola elimina parte central de la espera real del solicitante.']
  ],
  'cycle-time': [
    ['¿Desde qué punto se mide el cycle time?', ['Desde la solicitud del cliente', 'Desde que comienza el trabajo activo', 'Desde que se crea el dashboard', 'Desde el cierre del mes'], 1, 'El cycle time comienza cuando el equipo toma e inicia el trabajo.'],
    ['¿Qué ayuda a diagnosticar un cycle time elevado?', ['Retrabajos, bloqueos o pasos innecesarios', 'El tamaño del logo', 'El número de clientes nuevos', 'El presupuesto anual'], 0, 'Un ciclo largo sugiere fricciones dentro de la ejecución.'],
    ['Un pedido se solicita el lunes, inicia el jueves y termina el viernes. ¿Cuál es aproximadamente su cycle time?', ['Un día', 'Cuatro días', 'Cinco días', 'No puede calcularse'], 0, 'Desde el inicio del jueves hasta la finalización del viernes transcurre aproximadamente un día.'],
    ['¿Cómo se diferencia cycle time de lead time?', ['Cycle time mide desde el inicio; lead time desde la solicitud', 'Cycle time siempre es mayor', 'Lead time mide volumen', 'No hay diferencia'], 0, 'La diferencia clave es el punto de inicio de la medición.'],
    ['¿Qué dimensión del proceso representa principalmente el cycle time?', ['Velocidad de ejecución interna', 'Cantidad de trabajo pendiente', 'Volumen de trabajo terminado', 'Compromiso contractual'], 0, 'Mide la rapidez con la que el equipo completa trabajo una vez iniciado.'],
    ['Si el cycle time cae y la calidad también cae, la lectura correcta es:', ['La mejora de velocidad debe evaluarse junto con calidad', 'La operación mejoró sin dudas', 'El backlog dejó de importar', 'El SLA siempre aumentó'], 0, 'Una reducción de tiempo no es una mejora neta si viene acompañada de peor calidad.']
  ],
  backlog: [
    ['¿Qué representa el backlog?', ['Trabajo solicitado pero todavía no terminado', 'Solo trabajo ya cerrado', 'Tiempo de resolución', 'Porcentaje de cumplimiento'], 0, 'El backlog reúne los ítems pendientes, ya sea sin iniciar o en curso.'],
    ['Un backlog creciente sostenidamente suele indicar que:', ['Entra más trabajo del que se completa', 'Todos los SLA se cumplen', 'El cycle time es cero', 'No hay demanda'], 0, 'Si la llegada excede la salida, el trabajo pendiente se acumula.'],
    ['¿Qué segmentación aporta más valor al analizar backlog?', ['Antigüedad y prioridad', 'Color de la tarjeta', 'Nombre del reporte', 'Iniciales del equipo'], 0, 'La edad y la criticidad permiten detectar dónde está el riesgo real.'],
    ['Dos equipos tienen 50 ítems de backlog. ¿Qué dato puede hacer que sus riesgos sean muy distintos?', ['La antigüedad de los ítems', 'Que ambos usen el mismo gráfico', 'La hora de actualización', 'La longitud del nombre del equipo'], 0, 'Un backlog de casos recientes no tiene el mismo riesgo que uno de casos críticos muy atrasados.'],
    ['¿Qué combinación ayuda a entender la evolución del backlog?', ['Trabajo entrante y throughput', 'SLA y color de marca', 'Lead time y nombre del cliente', 'Solo cantidad de personas'], 0, 'Comparar entrada con salida explica si el stock pendiente crece o se reduce.'],
    ['¿Cuál es una lectura incompleta del backlog?', ['Mirar únicamente el total agregado', 'Analizar ítems por prioridad', 'Analizar la antigüedad', 'Observar su tendencia'], 0, 'El total puede ocultar casos críticos o muy antiguos que requieren atención.']
  ],
  sla: [
    ['¿Qué define un SLA?', ['Un compromiso medible de nivel de servicio', 'La cantidad total de trabajo pendiente', 'El tiempo desde una solicitud', 'El volumen de trabajo completado'], 0, 'Un SLA establece un estándar o promesa verificable de servicio.'],
    ['¿Cómo se calcula usualmente el porcentaje de cumplimiento de SLA?', ['Ítems dentro de SLA / ítems elegibles × 100', 'Ítems abiertos / ítems cerrados × 100', 'Horas activas / personas × 100', 'Lead time / cycle time × 100'], 0, 'Se compara la cantidad de casos que cumplieron con el total al que aplicaba el acuerdo.'],
    ['¿Por qué un tiempo promedio bajo no garantiza cumplimiento de SLA?', ['Puede ocultar algunos casos muy demorados', 'Porque SLA solo se calcula con throughput', 'Porque los promedios siempre son altos', 'Porque no se necesitan umbrales'], 0, 'El promedio puede ser bueno mientras una porción relevante incumple el umbral acordado.'],
    ['“Resolver 90% de tickets críticos en menos de 4 horas” es un ejemplo de:', ['SLA', 'Backlog', 'Cycle time', 'Throughput'], 0, 'Expresa población, umbral y porcentaje objetivo: los componentes de un SLA.'],
    ['¿Qué debe indicarse al reportar cumplimiento de SLA?', ['Período, población y condición de cumplimiento', 'Solo el color del indicador', 'Solo el promedio de tiempos', 'Solo el nombre del área'], 0, 'Sin población, período y regla no se puede interpretar correctamente el porcentaje.'],
    ['¿Qué análisis complementa mejor una caída en el cumplimiento de SLA?', ['Revisar los casos incumplidos por prioridad o causa', 'Cambiar la visualización', 'Eliminar los casos demorados', 'Mirar solo el promedio'], 0, 'Analizar los incumplimientos permite identificar causas y priorizar acciones.']
  ]
};

const storageKey = 'metricamente-operaciones-v1';
let progress = JSON.parse(localStorage.getItem(storageKey) || '{}');
let activeTopic, cardIndex = 0, quiz = [], questionIndex = 0, answers = [];
const $ = (selector) => document.querySelector(selector);

function save() { localStorage.setItem(storageKey, JSON.stringify(progress)); }
function show(name) { document.querySelectorAll('.view').forEach(v => v.classList.remove('active')); $(`#view-${name}`).classList.add('active'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
function level(score) { return score >= 75 ? 'Dominado' : score >= 50 ? 'En progreso' : 'Inicial'; }
function topicProgress(id) { return progress[id] || { attempts: 0, best: null, mistakes: [] }; }
function renderHome() {
  const studied = topics.filter(t => topicProgress(t.id).attempts).length;
  $('#route-progress').textContent = `${studied} de 5 conceptos estudiados`;
  $('#route-progress-bar').style.width = `${studied * 20}%`;
  $('#topic-grid').innerHTML = topics.map(t => { const p = topicProgress(t.id); const status = p.best === null ? 'Aún no estudiado' : `${level(p.best)} · mejor score ${p.best}%`; return `<button class="topic-card" type="button" data-topic="${t.id}"><span class="topic-icon">${t.icon}</span><h3>${t.name}</h3><p>${t.summary}</p><span class="topic-status">${status}</span></button>`; }).join('');
  document.querySelectorAll('[data-topic]').forEach(btn => btn.addEventListener('click', () => openStudy(btn.dataset.topic)));
}
function openStudy(id) { activeTopic = topics.find(t => t.id === id); cardIndex = 0; $('#study-title').textContent = activeTopic.name; $('#study-intro').textContent = activeTopic.intro; renderCard(); show('study'); }
function renderCard() { const card = activeTopic.cards[cardIndex]; $('#card-progress').innerHTML = activeTopic.cards.map((_, i) => `<span class="step ${i < cardIndex ? 'passed' : ''} ${i === cardIndex ? 'current' : ''}"></span>`).join(''); $('#study-card').innerHTML = `<span class="card-tag">Ficha ${cardIndex + 1} de ${activeTopic.cards.length} · ${card.tag}</span><h2>${card.title}</h2><p>${card.text}</p>${card.formula ? `<div class="formula">${card.formula}</div>` : ''}`; $('#previous-card').disabled = cardIndex === 0; $('#next-card').textContent = cardIndex === activeTopic.cards.length - 1 ? 'Comenzar quiz →' : 'Siguiente'; }
function startQuiz() { quiz = [...questionBank[activeTopic.id]].sort(() => Math.random() - .5).slice(0, 5); questionIndex = 0; answers = []; $('#quiz-title').textContent = activeTopic.name; renderQuestion(); show('quiz'); }
function renderQuestion() { const q = quiz[questionIndex]; $('#question-counter').textContent = `Pregunta ${questionIndex + 1} de ${quiz.length}`; $('#quiz-progress').style.width = `${(questionIndex / quiz.length) * 100}%`; $('#quiz-form').innerHTML = `<span class="question-kind">${activeTopic.name} · Opción múltiple</span><fieldset><legend>${q[0]}</legend>${q[1].map((option, i) => `<label class="option"><input type="radio" name="answer" value="${i}"><span>${option}</span></label>`).join('')}</fieldset><div class="question-actions"><button class="button primary" type="submit">${questionIndex === quiz.length - 1 ? 'Ver resultado' : 'Siguiente pregunta'}</button></div>`; }
function submitQuestion(event) { event.preventDefault(); const selected = $('#quiz-form input:checked'); if (!selected) { $('#quiz-form fieldset').animate?.([{ transform:'translateX(-4px)' },{ transform:'translateX(4px)' },{ transform:'translateX(0)' }], { duration:180 }); return; } answers.push(Number(selected.value)); questionIndex++; if (questionIndex < quiz.length) renderQuestion(); else showResult(); }
function getFeedback(score, mistakes) { const key = mistakes[0]; const next = topics.find(t => !topicProgress(t.id).attempts && t.id !== activeTopic.id) || topics.find(t => t.id !== activeTopic.id); if (score < 50) return `<p><strong>Conviene reconstruir la base antes de avanzar.</strong> Tu principal punto a reforzar es <strong>${key || activeTopic.name}</strong>. Repasá las fichas, prestando atención al momento de inicio de cada métrica y a qué decisión ayuda a tomar.</p><ul><li>Revisá las fichas de ${activeTopic.name}.</li><li>Intentá un nuevo quiz: las preguntas cambiarán.</li></ul>`;
  if (score < 75) return `<p><strong>La idea general está encaminada.</strong> Para consolidarla, repasá <strong>${key || activeTopic.name}</strong>: fue el concepto que apareció en tus respuestas incorrectas. Después repetí la evaluación para verificar que la distinción quedó clara.</p><ul><li>Volvé a las fichas relacionadas con tus errores.</li><li>Reintentá el quiz alternativo.</li></ul>`;
  return `<p><strong>Buen dominio de ${activeTopic.name}.</strong> Aplicaste correctamente los conceptos evaluados. Para ampliar tu mapa de Operaciones, el siguiente paso recomendado es <strong>${next.name}</strong>.</p><ul><li>Mantené presente la relación de esta métrica con calidad, capacidad y demanda.</li><li>Continuá con ${next.name} cuando estés listo.</li></ul>`;
}
function showResult() { const correct = answers.filter((a, i) => a === quiz[i][2]).length; const score = Math.round(correct / quiz.length * 100); const mistakes = quiz.filter((q, i) => answers[i] !== q[2]).map(q => activeTopic.name); const previous = topicProgress(activeTopic.id); progress[activeTopic.id] = { attempts: previous.attempts + 1, best: Math.max(previous.best ?? 0, score), mistakes: [...new Set(mistakes)] }; save(); $('#score-value').textContent = `${score}%`; $('#score-ring').style.background = `conic-gradient(var(--lime-dark) ${score * 3.6}deg, #dce2da 0deg)`; $('#result-summary').textContent = `${correct} de ${quiz.length} respuestas correctas.`; $('#level-badge').textContent = level(score); $('#feedback-content').innerHTML = getFeedback(score, mistakes); $('#answer-review').innerHTML = quiz.map((q, i) => { const ok = answers[i] === q[2]; return `<article class="review-item ${ok ? 'correct' : 'incorrect'}"><span class="review-status">${ok ? 'Correcta' : 'Para repasar'}</span><div class="review-question">${q[0]}</div><p>Tu respuesta: <strong>${q[1][answers[i]]}</strong>${ok ? '' : `<br>Respuesta correcta: <strong>${q[1][q[2]]}</strong>`}</p><p>${q[3]}</p></article>`; }).join(''); show('result'); }

$('#home-button').addEventListener('click', () => { renderHome(); show('home'); }); document.querySelectorAll('[data-go-home]').forEach(b => b.addEventListener('click', () => { renderHome(); show('home'); })); $('#previous-card').addEventListener('click', () => { if (cardIndex) { cardIndex--; renderCard(); } }); $('#next-card').addEventListener('click', () => { if (cardIndex === activeTopic.cards.length - 1) startQuiz(); else { cardIndex++; renderCard(); } }); $('#back-to-study').addEventListener('click', () => show('study')); $('#quiz-form').addEventListener('submit', submitQuestion); $('#retry-quiz').addEventListener('click', startQuiz); $('#continue-route').addEventListener('click', () => { renderHome(); show('home'); });
renderHome();
